id: IB49B24A3
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:21.812022
last_modified: 2023-01-04 11:29:21.812035
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  E2E8:
    title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
    base_file: E2E8.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
